# Generated by Django 4.2 on 2023-07-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0002_certification_contactmessage_education_experience_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Experience",
            new_name="WorkExperience",
        ),
    ]
